---
dependencies:
  appwrite: ^11.0.1
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  stripe_checkout: ^1.0.2
description: A Very Good Project created by Very Good CLI.
dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
environment:
  sdk: '>=3.1.0 <4.0.0'
flutter:
  generate: true
  uses-material-design: true
name: my_commerce
publish_to: none
version: 1.0.0+1